[variables]
    NIXPACKS_PHP_V = '8.3'

[phases.setup]
    nixPkgs = ['...', 'php83', 'php83Packages.composer', 'nodejs_20']

[phases.build]
    dependsOn = ['setup']
    cmds = [
        'composer install --no-dev --optimize-autoloader --no-interaction',
        'php artisan flux:publish --assets',
        'npm install',
        'npm run build'
        # Quitamos view:cache de aquí por ahora para que no trabe el deploy
    ]