[variables]
    NIXPACKS_PHP_V = '8.3'
    # Quitamos la variable de flags de aquí para manejarla directamente en el comando
    
[phases.setup]
    nixPkgs = ['...', 'php83', 'php83Packages.composer', 'nodejs_20']

[phases.build]
    dependsOn = ['setup']
    # Forzamos a que primero termine Composer y LUEGO corra NPM
    cmds = [
        'composer install --no-dev --optimize-autoloader --no-interaction --no-scripts',
        'npm install',
        'npm run build'
    ]